///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductsAttributesImagesDataAttributes {
/*
{
  "name": "msi2.jpeg",
  "alternativeText": "msi2.jpeg",
  "caption": "msi2.jpeg",
  "width": 960,
  "height": 769,
  "hash": "msi2_265609382e",
  "ext": ".jpeg",
  "mime": "image/jpeg",
  "size": 13.4,
  "url": "/uploads/msi2_265609382e.jpeg",
  "previewUrl": null,
  "provider": "local",
  "provider_metadata": null,
  "createdAt": "2022-11-14T19:53:59.514Z",
  "updatedAt": "2022-11-14T19:53:59.514Z"
} 
*/

  String? name;
  String? alternativeText;
  String? caption;
  int? width;
  int? height;
  String? hash;
  String? ext;
  String? mime;
  double? size;
  String? url;
  String? previewUrl;
  String? provider;
  String? providerMetadata;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesImagesDataAttributes({
    this.name,
    this.alternativeText,
    this.caption,
    this.width,
    this.height,
    this.hash,
    this.ext,
    this.mime,
    this.size,
    this.url,
    this.previewUrl,
    this.provider,
    this.providerMetadata,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesImagesDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    alternativeText = json['alternativeText']?.toString();
    caption = json['caption']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toInt();
    hash = json['hash']?.toString();
    ext = json['ext']?.toString();
    mime = json['mime']?.toString();
    size = json['size']?.toDouble();
    url = json['url']?.toString();
    previewUrl = json['previewUrl']?.toString();
    provider = json['provider']?.toString();
    providerMetadata = json['provider_metadata']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['alternativeText'] = alternativeText;
    data['caption'] = caption;
    data['width'] = width;
    data['height'] = height;
    data['hash'] = hash;
    data['ext'] = ext;
    data['mime'] = mime;
    data['size'] = size;
    data['url'] = url;
    data['previewUrl'] = previewUrl;
    data['provider'] = provider;
    data['provider_metadata'] = providerMetadata;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesImagesData {
/*
{
  "id": 2,
  "attributes": {
    "name": "msi2.jpeg",
    "alternativeText": "msi2.jpeg",
    "caption": "msi2.jpeg",
    "width": 960,
    "height": 769,
    "hash": "msi2_265609382e",
    "ext": ".jpeg",
    "mime": "image/jpeg",
    "size": 13.4,
    "url": "/uploads/msi2_265609382e.jpeg",
    "previewUrl": null,
    "provider": "local",
    "provider_metadata": null,
    "createdAt": "2022-11-14T19:53:59.514Z",
    "updatedAt": "2022-11-14T19:53:59.514Z"
  }
} 
*/

  int? id;
  ProductsAttributesImagesDataAttributes? attributes;

  ProductsAttributesImagesData({
    this.id,
    this.attributes,
  });
  ProductsAttributesImagesData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesImagesDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesImages {
/*
{
  "data": [
    {
      "id": 2,
      "attributes": {
        "name": "msi2.jpeg",
        "alternativeText": "msi2.jpeg",
        "caption": "msi2.jpeg",
        "width": 960,
        "height": 769,
        "hash": "msi2_265609382e",
        "ext": ".jpeg",
        "mime": "image/jpeg",
        "size": 13.4,
        "url": "/uploads/msi2_265609382e.jpeg",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2022-11-14T19:53:59.514Z",
        "updatedAt": "2022-11-14T19:53:59.514Z"
      }
    }
  ]
} 
*/

  List<ProductsAttributesImagesData?>? data;

  ProductsAttributesImages({
    this.data,
  });
  ProductsAttributesImages.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProductsAttributesImagesData>[];
      v.forEach((v) {
        arr0.add(ProductsAttributesImagesData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}

class ProductsAttributesCurrencyDataAttributes {
/*
{
  "name": "USD",
  "symbol": "$",
  "createdAt": "2022-11-06T12:40:35.522Z",
  "updatedAt": "2022-11-06T12:40:35.522Z"
} 
*/

  String? name;
  String? symbol;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesCurrencyDataAttributes({
    this.name,
    this.symbol,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesCurrencyDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    symbol = json['symbol']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['symbol'] = symbol;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesCurrencyData {
/*
{
  "id": 1,
  "attributes": {
    "name": "USD",
    "symbol": "$",
    "createdAt": "2022-11-06T12:40:35.522Z",
    "updatedAt": "2022-11-06T12:40:35.522Z"
  }
} 
*/

  int? id;
  ProductsAttributesCurrencyDataAttributes? attributes;

  ProductsAttributesCurrencyData({
    this.id,
    this.attributes,
  });
  ProductsAttributesCurrencyData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesCurrencyDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesCurrency {
/*
{
  "data": {
    "id": 1,
    "attributes": {
      "name": "USD",
      "symbol": "$",
      "createdAt": "2022-11-06T12:40:35.522Z",
      "updatedAt": "2022-11-06T12:40:35.522Z"
    }
  }
} 
*/

  ProductsAttributesCurrencyData? data;

  ProductsAttributesCurrency({
    this.data,
  });
  ProductsAttributesCurrency.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesCurrencyData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesStoreDataAttributes {
/*
{
  "name": "Xenon",
  "location": "Sana'a",
  "email": null,
  "phone": "777415208",
  "Description": null,
  "Link": null,
  "username": "Xenon",
  "createdAt": "2022-11-14T19:55:48.101Z",
  "updatedAt": "2022-11-14T19:55:48.101Z"
} 
*/

  String? name;
  String? location;
  String? email;
  String? phone;
  String? Description;
  String? Link;
  String? username;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesStoreDataAttributes({
    this.name,
    this.location,
    this.email,
    this.phone,
    this.Description,
    this.Link,
    this.username,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesStoreDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    location = json['location']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    Description = json['Description']?.toString();
    Link = json['Link']?.toString();
    username = json['username']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['location'] = location;
    data['email'] = email;
    data['phone'] = phone;
    data['Description'] = Description;
    data['Link'] = Link;
    data['username'] = username;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesStoreData {
/*
{
  "id": 1,
  "attributes": {
    "name": "Xenon",
    "location": "Sana'a",
    "email": null,
    "phone": "777415208",
    "Description": null,
    "Link": null,
    "username": "Xenon",
    "createdAt": "2022-11-14T19:55:48.101Z",
    "updatedAt": "2022-11-14T19:55:48.101Z"
  }
} 
*/

  int? id;
  ProductsAttributesStoreDataAttributes? attributes;

  ProductsAttributesStoreData({
    this.id,
    this.attributes,
  });
  ProductsAttributesStoreData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesStoreDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesStore {
/*
{
  "data": {
    "id": 1,
    "attributes": {
      "name": "Xenon",
      "location": "Sana'a",
      "email": null,
      "phone": "777415208",
      "Description": null,
      "Link": null,
      "username": "Xenon",
      "createdAt": "2022-11-14T19:55:48.101Z",
      "updatedAt": "2022-11-14T19:55:48.101Z"
    }
  }
} 
*/

  ProductsAttributesStoreData? data;

  ProductsAttributesStore({
    this.data,
  });
  ProductsAttributesStore.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesStoreData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesStockDataAttributes {
/*
{
  "createdAt": "2022-11-06T07:26:06.950Z",
  "updatedAt": "2022-11-06T07:26:06.950Z",
  "name": "available"
} 
*/

  String? createdAt;
  String? updatedAt;
  String? name;

  ProductsAttributesStockDataAttributes({
    this.createdAt,
    this.updatedAt,
    this.name,
  });
  ProductsAttributesStockDataAttributes.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['name'] = name;
    return data;
  }
}

class ProductsAttributesStockData {
/*
{
  "id": 2,
  "attributes": {
    "createdAt": "2022-11-06T07:26:06.950Z",
    "updatedAt": "2022-11-06T07:26:06.950Z",
    "name": "available"
  }
} 
*/

  int? id;
  ProductsAttributesStockDataAttributes? attributes;

  ProductsAttributesStockData({
    this.id,
    this.attributes,
  });
  ProductsAttributesStockData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesStockDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesStock {
/*
{
  "data": {
    "id": 2,
    "attributes": {
      "createdAt": "2022-11-06T07:26:06.950Z",
      "updatedAt": "2022-11-06T07:26:06.950Z",
      "name": "available"
    }
  }
} 
*/

  ProductsAttributesStockData? data;

  ProductsAttributesStock({
    this.data,
  });
  ProductsAttributesStock.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesStockData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesStatusDataAttributes {
/*
{
  "createdAt": "2022-11-06T07:27:55.346Z",
  "updatedAt": "2022-11-06T07:29:25.762Z",
  "name": "New"
} 
*/

  String? createdAt;
  String? updatedAt;
  String? name;

  ProductsAttributesStatusDataAttributes({
    this.createdAt,
    this.updatedAt,
    this.name,
  });
  ProductsAttributesStatusDataAttributes.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['name'] = name;
    return data;
  }
}

class ProductsAttributesStatusData {
/*
{
  "id": 1,
  "attributes": {
    "createdAt": "2022-11-06T07:27:55.346Z",
    "updatedAt": "2022-11-06T07:29:25.762Z",
    "name": "New"
  }
} 
*/

  int? id;
  ProductsAttributesStatusDataAttributes? attributes;

  ProductsAttributesStatusData({
    this.id,
    this.attributes,
  });
  ProductsAttributesStatusData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesStatusDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesStatus {
/*
{
  "data": {
    "id": 1,
    "attributes": {
      "createdAt": "2022-11-06T07:27:55.346Z",
      "updatedAt": "2022-11-06T07:29:25.762Z",
      "name": "New"
    }
  }
} 
*/

  ProductsAttributesStatusData? data;

  ProductsAttributesStatus({
    this.data,
  });
  ProductsAttributesStatus.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesStatusData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesScreenSizeDataAttributes {
/*
{
  "name": "15.6",
  "createdAt": "2022-11-06T07:33:59.942Z",
  "updatedAt": "2022-11-06T08:03:53.823Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesScreenSizeDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesScreenSizeDataAttributes.fromJson(
      Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesScreenSizeData {
/*
{
  "id": 5,
  "attributes": {
    "name": "15.6",
    "createdAt": "2022-11-06T07:33:59.942Z",
    "updatedAt": "2022-11-06T08:03:53.823Z"
  }
} 
*/

  int? id;
  ProductsAttributesScreenSizeDataAttributes? attributes;

  ProductsAttributesScreenSizeData({
    this.id,
    this.attributes,
  });
  ProductsAttributesScreenSizeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesScreenSizeDataAttributes.fromJson(
            json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesScreenSize {
/*
{
  "data": {
    "id": 5,
    "attributes": {
      "name": "15.6",
      "createdAt": "2022-11-06T07:33:59.942Z",
      "updatedAt": "2022-11-06T08:03:53.823Z"
    }
  }
} 
*/

  ProductsAttributesScreenSizeData? data;

  ProductsAttributesScreenSize({
    this.data,
  });
  ProductsAttributesScreenSize.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesScreenSizeData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesScreenRatioDataAttributes {
/*
{
  "name": "16:9",
  "createdAt": "2022-11-06T07:55:57.759Z",
  "updatedAt": "2022-11-06T07:55:57.759Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesScreenRatioDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesScreenRatioDataAttributes.fromJson(
      Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesScreenRatioData {
/*
{
  "id": 2,
  "attributes": {
    "name": "16:9",
    "createdAt": "2022-11-06T07:55:57.759Z",
    "updatedAt": "2022-11-06T07:55:57.759Z"
  }
} 
*/

  int? id;
  ProductsAttributesScreenRatioDataAttributes? attributes;

  ProductsAttributesScreenRatioData({
    this.id,
    this.attributes,
  });
  ProductsAttributesScreenRatioData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesScreenRatioDataAttributes.fromJson(
            json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesScreenRatio {
/*
{
  "data": {
    "id": 2,
    "attributes": {
      "name": "16:9",
      "createdAt": "2022-11-06T07:55:57.759Z",
      "updatedAt": "2022-11-06T07:55:57.759Z"
    }
  }
} 
*/

  ProductsAttributesScreenRatioData? data;

  ProductsAttributesScreenRatio({
    this.data,
  });
  ProductsAttributesScreenRatio.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesScreenRatioData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesOperatingSystemDataAttributes {
/*
{
  "name": "DOS",
  "createdAt": "2022-11-06T08:19:24.835Z",
  "updatedAt": "2022-11-06T08:19:24.835Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesOperatingSystemDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesOperatingSystemDataAttributes.fromJson(
      Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesOperatingSystemData {
/*
{
  "id": 6,
  "attributes": {
    "name": "DOS",
    "createdAt": "2022-11-06T08:19:24.835Z",
    "updatedAt": "2022-11-06T08:19:24.835Z"
  }
} 
*/

  int? id;
  ProductsAttributesOperatingSystemDataAttributes? attributes;

  ProductsAttributesOperatingSystemData({
    this.id,
    this.attributes,
  });
  ProductsAttributesOperatingSystemData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesOperatingSystemDataAttributes.fromJson(
            json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesOperatingSystem {
/*
{
  "data": {
    "id": 6,
    "attributes": {
      "name": "DOS",
      "createdAt": "2022-11-06T08:19:24.835Z",
      "updatedAt": "2022-11-06T08:19:24.835Z"
    }
  }
} 
*/

  ProductsAttributesOperatingSystemData? data;

  ProductsAttributesOperatingSystem({
    this.data,
  });
  ProductsAttributesOperatingSystem.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesOperatingSystemData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesRamSizeDataAttributes {
/*
{
  "name": "16",
  "createdAt": "2022-11-06T08:15:17.333Z",
  "updatedAt": "2022-11-06T08:15:17.333Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesRamSizeDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesRamSizeDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesRamSizeData {
/*
{
  "id": 4,
  "attributes": {
    "name": "16",
    "createdAt": "2022-11-06T08:15:17.333Z",
    "updatedAt": "2022-11-06T08:15:17.333Z"
  }
} 
*/

  int? id;
  ProductsAttributesRamSizeDataAttributes? attributes;

  ProductsAttributesRamSizeData({
    this.id,
    this.attributes,
  });
  ProductsAttributesRamSizeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesRamSizeDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesRamSize {
/*
{
  "data": {
    "id": 4,
    "attributes": {
      "name": "16",
      "createdAt": "2022-11-06T08:15:17.333Z",
      "updatedAt": "2022-11-06T08:15:17.333Z"
    }
  }
} 
*/

  ProductsAttributesRamSizeData? data;

  ProductsAttributesRamSize({
    this.data,
  });
  ProductsAttributesRamSize.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesRamSizeData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesRamSpeedDataAttributes {
/*
{
  "name": "4800",
  "createdAt": "2022-11-14T19:45:34.297Z",
  "updatedAt": "2022-11-14T19:45:34.297Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesRamSpeedDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesRamSpeedDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesRamSpeedData {
/*
{
  "id": 12,
  "attributes": {
    "name": "4800",
    "createdAt": "2022-11-14T19:45:34.297Z",
    "updatedAt": "2022-11-14T19:45:34.297Z"
  }
} 
*/

  int? id;
  ProductsAttributesRamSpeedDataAttributes? attributes;

  ProductsAttributesRamSpeedData({
    this.id,
    this.attributes,
  });
  ProductsAttributesRamSpeedData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesRamSpeedDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesRamSpeed {
/*
{
  "data": {
    "id": 12,
    "attributes": {
      "name": "4800",
      "createdAt": "2022-11-14T19:45:34.297Z",
      "updatedAt": "2022-11-14T19:45:34.297Z"
    }
  }
} 
*/

  ProductsAttributesRamSpeedData? data;

  ProductsAttributesRamSpeed({
    this.data,
  });
  ProductsAttributesRamSpeed.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesRamSpeedData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesRamTypeDataAttributes {
/*
{
  "name": "DDR5",
  "createdAt": "2022-11-06T08:07:58.409Z",
  "updatedAt": "2022-11-06T08:07:58.409Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesRamTypeDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesRamTypeDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesRamTypeData {
/*
{
  "id": 5,
  "attributes": {
    "name": "DDR5",
    "createdAt": "2022-11-06T08:07:58.409Z",
    "updatedAt": "2022-11-06T08:07:58.409Z"
  }
} 
*/

  int? id;
  ProductsAttributesRamTypeDataAttributes? attributes;

  ProductsAttributesRamTypeData({
    this.id,
    this.attributes,
  });
  ProductsAttributesRamTypeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesRamTypeDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesRamType {
/*
{
  "data": {
    "id": 5,
    "attributes": {
      "name": "DDR5",
      "createdAt": "2022-11-06T08:07:58.409Z",
      "updatedAt": "2022-11-06T08:07:58.409Z"
    }
  }
} 
*/

  ProductsAttributesRamTypeData? data;

  ProductsAttributesRamType({
    this.data,
  });
  ProductsAttributesRamType.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesRamTypeData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesScHardSize {
/*
{
  "data": null
} 
*/

  String? data;

  ProductsAttributesScHardSize({
    this.data,
  });
  ProductsAttributesScHardSize.fromJson(Map<String, dynamic> json) {
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data;
    return data;
  }
}

class ProductsAttributesScHardType {
/*
{
  "data": null
} 
*/

  String? data;

  ProductsAttributesScHardType({
    this.data,
  });
  ProductsAttributesScHardType.fromJson(Map<String, dynamic> json) {
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data;
    return data;
  }
}

class ProductsAttributesPrHardSizeDataAttributes {
/*
{
  "createdAt": "2022-11-06T08:29:44.664Z",
  "updatedAt": "2022-11-06T08:32:17.126Z",
  "name": "512GB"
} 
*/

  String? createdAt;
  String? updatedAt;
  String? name;

  ProductsAttributesPrHardSizeDataAttributes({
    this.createdAt,
    this.updatedAt,
    this.name,
  });
  ProductsAttributesPrHardSizeDataAttributes.fromJson(
      Map<String, dynamic> json) {
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['name'] = name;
    return data;
  }
}

class ProductsAttributesPrHardSizeData {
/*
{
  "id": 3,
  "attributes": {
    "createdAt": "2022-11-06T08:29:44.664Z",
    "updatedAt": "2022-11-06T08:32:17.126Z",
    "name": "512GB"
  }
} 
*/

  int? id;
  ProductsAttributesPrHardSizeDataAttributes? attributes;

  ProductsAttributesPrHardSizeData({
    this.id,
    this.attributes,
  });
  ProductsAttributesPrHardSizeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesPrHardSizeDataAttributes.fromJson(
            json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesPrHardSize {
/*
{
  "data": {
    "id": 3,
    "attributes": {
      "createdAt": "2022-11-06T08:29:44.664Z",
      "updatedAt": "2022-11-06T08:32:17.126Z",
      "name": "512GB"
    }
  }
} 
*/

  ProductsAttributesPrHardSizeData? data;

  ProductsAttributesPrHardSize({
    this.data,
  });
  ProductsAttributesPrHardSize.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesPrHardSizeData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesPrHardTypeDataAttributes {
/*
{
  "name": "SSD",
  "createdAt": "2022-11-06T08:24:39.137Z",
  "updatedAt": "2022-11-06T08:24:39.137Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesPrHardTypeDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesPrHardTypeDataAttributes.fromJson(
      Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesPrHardTypeData {
/*
{
  "id": 2,
  "attributes": {
    "name": "SSD",
    "createdAt": "2022-11-06T08:24:39.137Z",
    "updatedAt": "2022-11-06T08:24:39.137Z"
  }
} 
*/

  int? id;
  ProductsAttributesPrHardTypeDataAttributes? attributes;

  ProductsAttributesPrHardTypeData({
    this.id,
    this.attributes,
  });
  ProductsAttributesPrHardTypeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesPrHardTypeDataAttributes.fromJson(
            json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesPrHardType {
/*
{
  "data": {
    "id": 2,
    "attributes": {
      "name": "SSD",
      "createdAt": "2022-11-06T08:24:39.137Z",
      "updatedAt": "2022-11-06T08:24:39.137Z"
    }
  }
} 
*/

  ProductsAttributesPrHardTypeData? data;

  ProductsAttributesPrHardType({
    this.data,
  });
  ProductsAttributesPrHardType.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesPrHardTypeData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesCpuTypeDataAttributes {
/*
{
  "name": "Intel Core i7",
  "createdAt": "2022-11-06T08:08:10.464Z",
  "updatedAt": "2022-11-06T10:24:34.863Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesCpuTypeDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesCpuTypeDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesCpuTypeData {
/*
{
  "id": 3,
  "attributes": {
    "name": "Intel Core i7",
    "createdAt": "2022-11-06T08:08:10.464Z",
    "updatedAt": "2022-11-06T10:24:34.863Z"
  }
} 
*/

  int? id;
  ProductsAttributesCpuTypeDataAttributes? attributes;

  ProductsAttributesCpuTypeData({
    this.id,
    this.attributes,
  });
  ProductsAttributesCpuTypeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesCpuTypeDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesCpuType {
/*
{
  "data": {
    "id": 3,
    "attributes": {
      "name": "Intel Core i7",
      "createdAt": "2022-11-06T08:08:10.464Z",
      "updatedAt": "2022-11-06T10:24:34.863Z"
    }
  }
} 
*/

  ProductsAttributesCpuTypeData? data;

  ProductsAttributesCpuType({
    this.data,
  });
  ProductsAttributesCpuType.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesCpuTypeData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesBrandDataAttributes {
/*
{
  "name": "MSI",
  "createdAt": "2022-11-06T07:29:34.750Z",
  "updatedAt": "2022-11-06T07:29:34.750Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesBrandDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesBrandDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesBrandData {
/*
{
  "id": 12,
  "attributes": {
    "name": "MSI",
    "createdAt": "2022-11-06T07:29:34.750Z",
    "updatedAt": "2022-11-06T07:29:34.750Z"
  }
} 
*/

  int? id;
  ProductsAttributesBrandDataAttributes? attributes;

  ProductsAttributesBrandData({
    this.id,
    this.attributes,
  });
  ProductsAttributesBrandData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesBrandDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesBrand {
/*
{
  "data": {
    "id": 12,
    "attributes": {
      "name": "MSI",
      "createdAt": "2022-11-06T07:29:34.750Z",
      "updatedAt": "2022-11-06T07:29:34.750Z"
    }
  }
} 
*/

  ProductsAttributesBrandData? data;

  ProductsAttributesBrand({
    this.data,
  });
  ProductsAttributesBrand.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesBrandData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributesTypeDataAttributes {
/*
{
  "name": "Laptop",
  "createdAt": "2022-11-06T07:19:28.156Z",
  "updatedAt": "2022-11-06T07:19:28.156Z"
} 
*/

  String? name;
  String? createdAt;
  String? updatedAt;

  ProductsAttributesTypeDataAttributes({
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  ProductsAttributesTypeDataAttributes.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ProductsAttributesTypeData {
/*
{
  "id": 1,
  "attributes": {
    "name": "Laptop",
    "createdAt": "2022-11-06T07:19:28.156Z",
    "updatedAt": "2022-11-06T07:19:28.156Z"
  }
} 
*/

  int? id;
  ProductsAttributesTypeDataAttributes? attributes;

  ProductsAttributesTypeData({
    this.id,
    this.attributes,
  });
  ProductsAttributesTypeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributesTypeDataAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProductsAttributesType {
/*
{
  "data": {
    "id": 1,
    "attributes": {
      "name": "Laptop",
      "createdAt": "2022-11-06T07:19:28.156Z",
      "updatedAt": "2022-11-06T07:19:28.156Z"
    }
  }
} 
*/

  ProductsAttributesTypeData? data;

  ProductsAttributesType({
    this.data,
  });
  ProductsAttributesType.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ProductsAttributesTypeData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProductsAttributes {
/*
{
  "model": "Gaming pulse GL66 12UEK",
  "createdAt": "2022-11-14T19:54:12.371Z",
  "updatedAt": "2022-11-15T10:31:09.711Z",
  "cpu_gen": "12",
  "price": "1400",
  "type": {
    "data": {
      "id": 1,
      "attributes": {
        "name": "Laptop",
        "createdAt": "2022-11-06T07:19:28.156Z",
        "updatedAt": "2022-11-06T07:19:28.156Z"
      }
    }
  },
  "brand": {
    "data": {
      "id": 12,
      "attributes": {
        "name": "MSI",
        "createdAt": "2022-11-06T07:29:34.750Z",
        "updatedAt": "2022-11-06T07:29:34.750Z"
      }
    }
  },
  "cpu_type": {
    "data": {
      "id": 3,
      "attributes": {
        "name": "Intel Core i7",
        "createdAt": "2022-11-06T08:08:10.464Z",
        "updatedAt": "2022-11-06T10:24:34.863Z"
      }
    }
  },
  "pr_hard_type": {
    "data": {
      "id": 2,
      "attributes": {
        "name": "SSD",
        "createdAt": "2022-11-06T08:24:39.137Z",
        "updatedAt": "2022-11-06T08:24:39.137Z"
      }
    }
  },
  "pr_hard_size": {
    "data": {
      "id": 3,
      "attributes": {
        "createdAt": "2022-11-06T08:29:44.664Z",
        "updatedAt": "2022-11-06T08:32:17.126Z",
        "name": "512GB"
      }
    }
  },
  "sc_hard_type": {
    "data": null
  },
  "sc_hard_size": {
    "data": null
  },
  "ram_type": {
    "data": {
      "id": 5,
      "attributes": {
        "name": "DDR5",
        "createdAt": "2022-11-06T08:07:58.409Z",
        "updatedAt": "2022-11-06T08:07:58.409Z"
      }
    }
  },
  "ram_speed": {
    "data": {
      "id": 12,
      "attributes": {
        "name": "4800",
        "createdAt": "2022-11-14T19:45:34.297Z",
        "updatedAt": "2022-11-14T19:45:34.297Z"
      }
    }
  },
  "ram_size": {
    "data": {
      "id": 4,
      "attributes": {
        "name": "16",
        "createdAt": "2022-11-06T08:15:17.333Z",
        "updatedAt": "2022-11-06T08:15:17.333Z"
      }
    }
  },
  "operating_system": {
    "data": {
      "id": 6,
      "attributes": {
        "name": "DOS",
        "createdAt": "2022-11-06T08:19:24.835Z",
        "updatedAt": "2022-11-06T08:19:24.835Z"
      }
    }
  },
  "screen_ratio": {
    "data": {
      "id": 2,
      "attributes": {
        "name": "16:9",
        "createdAt": "2022-11-06T07:55:57.759Z",
        "updatedAt": "2022-11-06T07:55:57.759Z"
      }
    }
  },
  "screen_size": {
    "data": {
      "id": 5,
      "attributes": {
        "name": "15.6",
        "createdAt": "2022-11-06T07:33:59.942Z",
        "updatedAt": "2022-11-06T08:03:53.823Z"
      }
    }
  },
  "status": {
    "data": {
      "id": 1,
      "attributes": {
        "createdAt": "2022-11-06T07:27:55.346Z",
        "updatedAt": "2022-11-06T07:29:25.762Z",
        "name": "New"
      }
    }
  },
  "stock": {
    "data": {
      "id": 2,
      "attributes": {
        "createdAt": "2022-11-06T07:26:06.950Z",
        "updatedAt": "2022-11-06T07:26:06.950Z",
        "name": "available"
      }
    }
  },
  "store": {
    "data": {
      "id": 1,
      "attributes": {
        "name": "Xenon",
        "location": "Sana'a",
        "email": null,
        "phone": "777415208",
        "Description": null,
        "Link": null,
        "username": "Xenon",
        "createdAt": "2022-11-14T19:55:48.101Z",
        "updatedAt": "2022-11-14T19:55:48.101Z"
      }
    }
  },
  "currency": {
    "data": {
      "id": 1,
      "attributes": {
        "name": "USD",
        "symbol": "$",
        "createdAt": "2022-11-06T12:40:35.522Z",
        "updatedAt": "2022-11-06T12:40:35.522Z"
      }
    }
  },
  "images": {
    "data": [
      {
        "id": 2,
        "attributes": {
          "name": "msi2.jpeg",
          "alternativeText": "msi2.jpeg",
          "caption": "msi2.jpeg",
          "width": 960,
          "height": 769,
          "hash": "msi2_265609382e",
          "ext": ".jpeg",
          "mime": "image/jpeg",
          "size": 13.4,
          "url": "/uploads/msi2_265609382e.jpeg",
          "previewUrl": null,
          "provider": "local",
          "provider_metadata": null,
          "createdAt": "2022-11-14T19:53:59.514Z",
          "updatedAt": "2022-11-14T19:53:59.514Z"
        }
      }
    ]
  }
} 
*/

  String? model;
  String? createdAt;
  String? updatedAt;
  String? cpuGen;
  String? price;
  ProductsAttributesType? type;
  ProductsAttributesBrand? brand;
  ProductsAttributesCpuType? cpuType;
  ProductsAttributesPrHardType? prHardType;
  ProductsAttributesPrHardSize? prHardSize;
  ProductsAttributesScHardType? scHardType;
  ProductsAttributesScHardSize? scHardSize;
  ProductsAttributesRamType? ramType;
  ProductsAttributesRamSpeed? ramSpeed;
  ProductsAttributesRamSize? ramSize;
  ProductsAttributesOperatingSystem? operatingSystem;
  ProductsAttributesScreenRatio? screenRatio;
  ProductsAttributesScreenSize? screenSize;
  ProductsAttributesStatus? status;
  ProductsAttributesStock? stock;
  ProductsAttributesStore? store;
  ProductsAttributesCurrency? currency;
  ProductsAttributesImages? images;

  ProductsAttributes({
    this.model,
    this.createdAt,
    this.updatedAt,
    this.cpuGen,
    this.price,
    this.type,
    this.brand,
    this.cpuType,
    this.prHardType,
    this.prHardSize,
    this.scHardType,
    this.scHardSize,
    this.ramType,
    this.ramSpeed,
    this.ramSize,
    this.operatingSystem,
    this.screenRatio,
    this.screenSize,
    this.status,
    this.stock,
    this.store,
    this.currency,
    this.images,
  });
  ProductsAttributes.fromJson(Map<String, dynamic> json) {
    model = json['model']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    cpuGen = json['cpu_gen']?.toString();
    price = json['price']?.toString();
    type = (json['type'] != null)
        ? ProductsAttributesType.fromJson(json['type'])
        : null;
    brand = (json['brand'] != null)
        ? ProductsAttributesBrand.fromJson(json['brand'])
        : null;
    cpuType = (json['cpu_type'] != null)
        ? ProductsAttributesCpuType.fromJson(json['cpu_type'])
        : null;
    prHardType = (json['pr_hard_type'] != null)
        ? ProductsAttributesPrHardType.fromJson(json['pr_hard_type'])
        : null;
    prHardSize = (json['pr_hard_size'] != null)
        ? ProductsAttributesPrHardSize.fromJson(json['pr_hard_size'])
        : null;
    scHardType = (json['sc_hard_type'] != null)
        ? ProductsAttributesScHardType.fromJson(json['sc_hard_type'])
        : null;
    scHardSize = (json['sc_hard_size'] != null)
        ? ProductsAttributesScHardSize.fromJson(json['sc_hard_size'])
        : null;
    ramType = (json['ram_type'] != null)
        ? ProductsAttributesRamType.fromJson(json['ram_type'])
        : null;
    ramSpeed = (json['ram_speed'] != null)
        ? ProductsAttributesRamSpeed.fromJson(json['ram_speed'])
        : null;
    ramSize = (json['ram_size'] != null)
        ? ProductsAttributesRamSize.fromJson(json['ram_size'])
        : null;
    operatingSystem = (json['operating_system'] != null)
        ? ProductsAttributesOperatingSystem.fromJson(json['operating_system'])
        : null;
    screenRatio = (json['screen_ratio'] != null)
        ? ProductsAttributesScreenRatio.fromJson(json['screen_ratio'])
        : null;
    screenSize = (json['screen_size'] != null)
        ? ProductsAttributesScreenSize.fromJson(json['screen_size'])
        : null;
    status = (json['status'] != null)
        ? ProductsAttributesStatus.fromJson(json['status'])
        : null;
    stock = (json['stock'] != null)
        ? ProductsAttributesStock.fromJson(json['stock'])
        : null;
    store = (json['store'] != null)
        ? ProductsAttributesStore.fromJson(json['store'])
        : null;
    currency = (json['currency'] != null)
        ? ProductsAttributesCurrency.fromJson(json['currency'])
        : null;
    images = (json['images'] != null)
        ? ProductsAttributesImages.fromJson(json['images'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['model'] = model;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['cpu_gen'] = cpuGen;
    data['price'] = price;
    if (type != null) {
      data['type'] = type!.toJson();
    }
    if (brand != null) {
      data['brand'] = brand!.toJson();
    }
    if (cpuType != null) {
      data['cpu_type'] = cpuType!.toJson();
    }
    if (prHardType != null) {
      data['pr_hard_type'] = prHardType!.toJson();
    }
    if (prHardSize != null) {
      data['pr_hard_size'] = prHardSize!.toJson();
    }
    if (scHardType != null) {
      data['sc_hard_type'] = scHardType!.toJson();
    }
    if (scHardSize != null) {
      data['sc_hard_size'] = scHardSize!.toJson();
    }
    if (ramType != null) {
      data['ram_type'] = ramType!.toJson();
    }
    if (ramSpeed != null) {
      data['ram_speed'] = ramSpeed!.toJson();
    }
    if (ramSize != null) {
      data['ram_size'] = ramSize!.toJson();
    }
    if (operatingSystem != null) {
      data['operating_system'] = operatingSystem!.toJson();
    }
    if (screenRatio != null) {
      data['screen_ratio'] = screenRatio!.toJson();
    }
    if (screenSize != null) {
      data['screen_size'] = screenSize!.toJson();
    }
    if (status != null) {
      data['status'] = status!.toJson();
    }
    if (stock != null) {
      data['stock'] = stock!.toJson();
    }
    if (store != null) {
      data['store'] = store!.toJson();
    }
    if (currency != null) {
      data['currency'] = currency!.toJson();
    }
    if (images != null) {
      data['images'] = images!.toJson();
    }
    return data;
  }
}

class Products {
/*
{
  "id": 2,
  "attributes": {
    "model": "Gaming pulse GL66 12UEK",
    "createdAt": "2022-11-14T19:54:12.371Z",
    "updatedAt": "2022-11-15T10:31:09.711Z",
    "cpu_gen": "12",
    "price": "1400",
    "type": {
      "data": {
        "id": 1,
        "attributes": {
          "name": "Laptop",
          "createdAt": "2022-11-06T07:19:28.156Z",
          "updatedAt": "2022-11-06T07:19:28.156Z"
        }
      }
    },
    "brand": {
      "data": {
        "id": 12,
        "attributes": {
          "name": "MSI",
          "createdAt": "2022-11-06T07:29:34.750Z",
          "updatedAt": "2022-11-06T07:29:34.750Z"
        }
      }
    },
    "cpu_type": {
      "data": {
        "id": 3,
        "attributes": {
          "name": "Intel Core i7",
          "createdAt": "2022-11-06T08:08:10.464Z",
          "updatedAt": "2022-11-06T10:24:34.863Z"
        }
      }
    },
    "pr_hard_type": {
      "data": {
        "id": 2,
        "attributes": {
          "name": "SSD",
          "createdAt": "2022-11-06T08:24:39.137Z",
          "updatedAt": "2022-11-06T08:24:39.137Z"
        }
      }
    },
    "pr_hard_size": {
      "data": {
        "id": 3,
        "attributes": {
          "createdAt": "2022-11-06T08:29:44.664Z",
          "updatedAt": "2022-11-06T08:32:17.126Z",
          "name": "512GB"
        }
      }
    },
    "sc_hard_type": {
      "data": null
    },
    "sc_hard_size": {
      "data": null
    },
    "ram_type": {
      "data": {
        "id": 5,
        "attributes": {
          "name": "DDR5",
          "createdAt": "2022-11-06T08:07:58.409Z",
          "updatedAt": "2022-11-06T08:07:58.409Z"
        }
      }
    },
    "ram_speed": {
      "data": {
        "id": 12,
        "attributes": {
          "name": "4800",
          "createdAt": "2022-11-14T19:45:34.297Z",
          "updatedAt": "2022-11-14T19:45:34.297Z"
        }
      }
    },
    "ram_size": {
      "data": {
        "id": 4,
        "attributes": {
          "name": "16",
          "createdAt": "2022-11-06T08:15:17.333Z",
          "updatedAt": "2022-11-06T08:15:17.333Z"
        }
      }
    },
    "operating_system": {
      "data": {
        "id": 6,
        "attributes": {
          "name": "DOS",
          "createdAt": "2022-11-06T08:19:24.835Z",
          "updatedAt": "2022-11-06T08:19:24.835Z"
        }
      }
    },
    "screen_ratio": {
      "data": {
        "id": 2,
        "attributes": {
          "name": "16:9",
          "createdAt": "2022-11-06T07:55:57.759Z",
          "updatedAt": "2022-11-06T07:55:57.759Z"
        }
      }
    },
    "screen_size": {
      "data": {
        "id": 5,
        "attributes": {
          "name": "15.6",
          "createdAt": "2022-11-06T07:33:59.942Z",
          "updatedAt": "2022-11-06T08:03:53.823Z"
        }
      }
    },
    "status": {
      "data": {
        "id": 1,
        "attributes": {
          "createdAt": "2022-11-06T07:27:55.346Z",
          "updatedAt": "2022-11-06T07:29:25.762Z",
          "name": "New"
        }
      }
    },
    "stock": {
      "data": {
        "id": 2,
        "attributes": {
          "createdAt": "2022-11-06T07:26:06.950Z",
          "updatedAt": "2022-11-06T07:26:06.950Z",
          "name": "available"
        }
      }
    },
    "store": {
      "data": {
        "id": 1,
        "attributes": {
          "name": "Xenon",
          "location": "Sana'a",
          "email": null,
          "phone": "777415208",
          "Description": null,
          "Link": null,
          "username": "Xenon",
          "createdAt": "2022-11-14T19:55:48.101Z",
          "updatedAt": "2022-11-14T19:55:48.101Z"
        }
      }
    },
    "currency": {
      "data": {
        "id": 1,
        "attributes": {
          "name": "USD",
          "symbol": "$",
          "createdAt": "2022-11-06T12:40:35.522Z",
          "updatedAt": "2022-11-06T12:40:35.522Z"
        }
      }
    },
    "images": {
      "data": [
        {
          "id": 2,
          "attributes": {
            "name": "msi2.jpeg",
            "alternativeText": "msi2.jpeg",
            "caption": "msi2.jpeg",
            "width": 960,
            "height": 769,
            "hash": "msi2_265609382e",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 13.4,
            "url": "/uploads/msi2_265609382e.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "createdAt": "2022-11-14T19:53:59.514Z",
            "updatedAt": "2022-11-14T19:53:59.514Z"
          }
        }
      ]
    }
  }
} 
*/

  int? id;
  ProductsAttributes? attributes;

  Products({
    this.id,
    this.attributes,
  });
  Products.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null)
        ? ProductsAttributes.fromJson(json['attributes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}
